import type { DocumentType } from "../../lib/documents";

export const TYPE_ACCENT: Partial<Record<DocumentType, string>> = {
  decree: "bg-stamp-red",
  memo: "bg-amber-crt",
  incident: "bg-stamp-red",
  forensic: "bg-cyan-crt",
  autopsy: "bg-cyan-crt",
  interrogation: "bg-amber-crt",
  ai_log: "bg-cyan-crt",
  news: "bg-paper-foreground",
  bulletin: "bg-stamp-red",
  transmission: "bg-cyan-crt",
  bounty: "bg-stamp-red",
  manifesto: "bg-stamp-red",
  broadcast: "bg-amber-crt",
  order: "bg-stamp-red",
  dossier: "bg-amber-crt",
  id_card: "bg-cyan-crt",
  foreign_letter: "bg-amber-crt",
  batch: "bg-stamp-red",
  propaganda: "bg-stamp-red",
  monitored_thread: "bg-cyan-crt",
  codex_entry: "bg-stamp-red",
  medical_record: "bg-cyan-crt",
  classified_project: "bg-stamp-red",
};
